### PR TITLE
Ac department details

### PR DESCRIPTION
**Pull request by allisonkatecollins**
Closes Ticket #7 

User can see department details; details page has name of dept as header and shows list of employees assigned to that department.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions for Change Made

git fetch --all
git checkout ac-department-details
run BangazonWorkforce
in nav bar: Departments --> Details
Details page should have department name as a header, followed by list of employees within dept

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Daniel-Brewer — DISMISSED** [review]
I get an exception when I click on a created program's details. I also noticed that all departments, including created ones have the same employee count size

**Comment by allisonkatecollins** [comment]
fixed null error and employee count error!

**Review by Daniel-Brewer — APPROVED** [review]
Looks Fantastic! Awesome Job!

**Review by loetek — APPROVED** [review]
It's fine I guess....... Approved!

**Review by hannahmneal — APPROVED** [review]
Good job - Departments can be viewed as a list and the employees in the department can be seen when details link is clicked on. If an employee is newly created they can be seen in the department list too.

**Pull request merged**
