### PR TITLE
employee list is displaying

### PR DESCRIPTION
**Pull request by Daniel-Brewer**
# Description

Added code to EmployeesController to display employee list

## Type of change

- [X ] New feature (non-breaking change which adds functionality)

# Testing Instructions for Change Made

git fetch-all
git checkout db-employee-list
execute BangazonWorkforce
Click on Employees in NavBar
A list of employees should appear

# Checklist:

- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] My changes generate no new warnings
- [X ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by hannahmneal — APPROVED** [review]
Looks good - the list of employees is available with the seed data we are using. Great job!

**Review by allisonkatecollins — APPROVED** [review]
looks gr8

**Comment by hannahmneal** [comment]
https://github.com/nss-crystal-cobras/WorkforceManagement/issues/1

**Review by MissPeperr — APPROVED** [review]
I'll let it slide that you didn't link to your ticket in your PR 😎 Looks good! 👍

**Pull request merged**
