### PR TITLE
Computer jd#8

### LINKED ISSUE #4: This ticket has been separated into 4.1 and 4.2 ****HR should be able to edit an employee
## Acceptance Criteria

**Given** user is viewing an employee
**When** user clicks on the Edit link
**Then** user should be able to edit the last name of the employee
**Or** change the department to which the employee is assigned
**Or** change the computer assigned to the employee
**Or** add/remove training programs for the employee to attend in the future

### LINKED ISSUE #8: IT should be able to view, create and delete computers
## Acceptance Criteria

**Given** a user wants to view all computers
**When** the user clicks on the Computers item in the navigation bar
**Then** the user should see a list of all computers
**And** each item should be a hyperlink that can be clicked to view the details

**Given** a user is viewing all computers
**When** the user clicks the Create New link
**Then** the user should be presented with a form in which the following information can be entered

1. Computer manufacturer
1. Computer make
1. Purchase date

**Given** user is viewing a single computer
**When** the user clicks on the Delete link
**Then** the user should be presented with a screen to verify that it should be deleted
**And** if the user chooses Yes from that screen, the computer should be deleted **only if it is has never been assigned to an employee**

### PR DESCRIPTION
**Pull request by loetek**
# Description
**Computer**  you should be able to Create, View, and Delete.

Closes #8 (https://github.com/nss-crystal-cobras/WorkforceManagement/issues/8) 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Testing Instructions

git fetch --all
git checkout ComputerJD#8
At this point, you will want to check and see if Computers View, Create, and Delete work properly.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by allisonkatecollins — APPROVED** [review]
looks gr8

**Review by hannahmneal — APPROVED** [review]
The create and view are fine but there is still a problem with the delete; I can delete a newly-created item but I cannot delete one that already exists (one that I did not create a minute beforehand).

**Review by hannahmneal — CHANGES_REQUESTED** [review]
My last comment was supposed to be one requesting changes, not approving! I clicked the wrong button, sorry!

**Review by hannahmneal — CHANGES_REQUESTED** [review]
Delete is functional if the computer is not associated with an employee. However: 
- if a computer is associated with an employee and the "delete" is clicked, the computer and employee information disappear (leaving only table/list headings) and 
- - the page does not redirect to the computer list and  
- - the computer is not removed from the list

The create is working since a newly-created computer has no employee and can be deleted. 

All Edit buttons (from the list view and computer view) result in an error.

**Review by hannahmneal — APPROVED** [review]

**Pull request merged**
