### PR TITLE
Hannah employee details

### PR DESCRIPTION
**Pull request by hannahmneal**
PR Template: # Description

Issue #3:  https://github.com/nss-crystal-cobras/WorkforceManagement/issues/3

Implemented Employee Details functionality (a user can view the employee's name, training programs enrolled in (if applicable), department to which they are assigned, and current computer.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions for Change Made

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

```git fetch --all```
```git checkout hannah-employee-details```
Please Click "Employees" from the nav.
From the list of employees, please click on the following people:
- Allison Collins (verify name, department, a single training program, department and computer are visible)
- Nick Hansen (verify name, computer and department are visible; verify that training program information is missing)
- Hunter Daddy (verify name, computer, department are visible and that two training programs are visible)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Daniel-Brewer — APPROVED** [review]
Works beautifully, great job!

**Comment by allisonkatecollins** [comment]
You're getting the appropriate info and not throwing errors, but I'd delete some of the info being displayed - the Id's of the employee and computer, and then there are two empty categories for "name" and "startdate". Maybe also change the display name for some of the categories for clarification.

**Comment by hannahmneal** [comment]
@allisonkatecollins : I have created a separate issue ticket for your suggestions. The current code fulfills this ticket but your suggestions would lead to a more user-friendly interface and should probably be implemented.

**Comment by hannahmneal** [comment]
The requested changes have been made to improve the user interface for employee details.

**Comment by hannahmneal** [comment]
Allison also noticed that the Department Names were not displayed with the Employee list (when clicking "Employees" from the nav menu). This has also been resolved.

**Review by allisonkatecollins — APPROVED** [review]
looks good! thanks for dealing with me :~)

**Pull request merged**
