### PR TITLE
Ac add employee

### LINKED ISSUE #2: HR should be able to add an employee
## Acceptance Criteria

**Given** the user is viewing the list of employees
**When** the user clicks the Create New link
**Then** a form for be displayed on which the following information can be entered

1. First name
1. Last name
1. Is the employee a supervisor
1. Select a department from a drop down

### PR DESCRIPTION
**Pull request by allisonkatecollins**
Closes [Ticket #2](https://github.com/nss-crystal-cobras/WorkforceManagement/issues/2)

User can create a new employee. Create form includes first name, last name, is supervisor, and department selection.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Testing Instructions for Change Made

git fetch --all
git checkout ac-add-employee
run BangazonWorkforce
go to Employees tab on the nav bar
Click Create New and fill out all fields
Try creating employee without filling out a name field; you should get an error message

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Daniel-Brewer — APPROVED** [review]
Works great! Awesome job!

**Review by loetek — COMMENTED** [review]
Not seeing a link to the ticket AK

**Review by loetek — APPROVED** [review]
This is GLORIOUS!!!! APPROVED

**Review by MissPeperr — APPROVED** [review]
Nice link! 😄 Approved! 👍

**Pull request merged**
